
title: Joo's Blog
email: jookid94@gmail.com
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "parkjoohwan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: parkjoohwan

# Build settings
markdown: kramdown
theme: minima
highliter: rouge
plugins:
  - jekyll-feed