
title: Joo's Blog
email: jookid94@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "parkjoohwan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: parkjoohwan

# Build settings
markdown: kramdown
theme: minima
highliter: rouge
plugins:
  - jekyll-feed